// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"


///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Panel2;
void ui_event_starstopbutton(lv_event_t * e);
lv_obj_t * ui_starstopbutton;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Spinner1;
void ui_event_modebutton(lv_event_t * e);
lv_obj_t * ui_modebutton;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_Image3;
lv_obj_t * ui_Label3;
void ui_event_rotationbutton(lv_event_t * e);
lv_obj_t * ui_rotationbutton;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_Image5;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Panel6;
lv_obj_t * ui_Image6;
void ui_event_speedchange(lv_event_t * e);
lv_obj_t * ui_speedchange;
lv_obj_t * ui_Panel7;
lv_obj_t * ui_Image7;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Label7;
void ui_event_modebutton4(lv_event_t * e);
lv_obj_t * ui_modebutton4;
lv_obj_t * ui_Label13;
void ui_event_modebutton5(lv_event_t * e);
lv_obj_t * ui_modebutton5;
lv_obj_t * ui_Label14;
lv_obj_t * ui_Panel11;
lv_obj_t * ui_Label11;
void ui_event_speedchange2(lv_event_t * e);
lv_obj_t * ui_speedchange2;
lv_obj_t * ui_Panel12;
lv_obj_t * ui_Image11;
lv_obj_t * ui_Label17;
lv_obj_t * ui_Label15;
void ui_event_modebutton6(lv_event_t * e);
lv_obj_t * ui_modebutton6;
lv_obj_t * ui_Label19;
lv_obj_t * ui_Panel13;
lv_obj_t * ui_Image10;
lv_obj_t * ui_Label16;
void ui_event_modebutton7(lv_event_t * e);
lv_obj_t * ui_modebutton7;
lv_obj_t * ui_Label20;
void ui_event_customsetupbutton(lv_event_t * e);
lv_obj_t * ui_customsetupbutton;
lv_obj_t * ui_Label23;
lv_obj_t * ui_Panel15;
lv_obj_t * ui_Label21;
void ui_event_settingsbutton(lv_event_t * e);
lv_obj_t * ui_settingsbutton;
lv_obj_t * ui_nasrojochki;


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t * ui_Screen2;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_Button2;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Panel8;
lv_obj_t * ui_Panel10;
lv_obj_t * ui_Image4;
lv_obj_t * ui_Image8;
lv_obj_t * ui_modebutton2;
lv_obj_t * ui_Label12;
lv_obj_t * ui_cleanbutton;
lv_obj_t * ui_Labelclean;
lv_obj_t * ui_eneterbutton;
lv_obj_t * ui_enterlabel;
lv_obj_t * ui_Panelline2;
lv_obj_t * ui_Panelline3;
lv_obj_t * ui_Panelline4;
lv_obj_t * ui_Panelline5;
lv_obj_t * ui_Panelline6;
lv_obj_t * ui_Panelline7;
lv_obj_t * ui_Panelline8;
lv_obj_t * ui_Panelline9;
lv_obj_t * ui_Panelline10;
lv_obj_t * ui_Panelline11;
lv_obj_t * ui_Panelline12;
lv_obj_t * ui_Panelline13;
lv_obj_t * ui_Panelline14;
lv_obj_t * ui_Panelline15;
lv_obj_t * ui_Panelline16;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Keyboard1;
void ui_eventhandler_modebutton3(lv_event_t * e);
lv_obj_t * ui_modebutton3;
lv_obj_t * ui_Image9;
lv_obj_t * ui_TextArea1;
lv_obj_t * ui____initial_actions0;
void ui_event_modebutton2(lv_event_t * e);
lv_obj_t * ui_modebutton2;
lv_obj_t * ui_Label12;
void ui_event_modebutton3(lv_event_t *e);

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
lv_obj_t * ui_Screen3;
lv_obj_t * ui_programbutton;
lv_obj_t * ui_Label18;
lv_obj_t * ui_programbutton2;
lv_obj_t * ui_Label22;
lv_obj_t * ui_programbutton3;
lv_obj_t * ui_Label23;
lv_obj_t * ui_programbutton4;
lv_obj_t * ui_Label24;
lv_obj_t * ui_programbutton5;
lv_obj_t * ui_Label25;
lv_obj_t * ui_programbutton6;
lv_obj_t * ui_Label26;
void ui_event_Button6(lv_event_t * e);
lv_obj_t * ui_Button6;
lv_obj_t * ui_Panel14;
lv_obj_t * ui_Image13;
lv_obj_t * ui_Label21;

// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
lv_obj_t * ui_Screen4;
void ui_event_Button7(lv_event_t * e);
lv_obj_t * ui_Button7;
lv_obj_t * ui_Panel15;
lv_obj_t * ui_Image12;
void ui_event_Button4(lv_event_t * e);
lv_obj_t * ui_Button4;
lv_obj_t * ui_Panel16;
lv_obj_t * ui_Image15;
lv_obj_t * ui_Label28;
void ui_event_speedchange3(lv_event_t * e);
lv_obj_t * ui_speedchange3;
lv_obj_t * ui_Panel17;
lv_obj_t * ui_Image16;
lv_obj_t * ui_Label30;
lv_obj_t * ui_Label27;
void ui_event_rotationbutton2(lv_event_t * e);
lv_obj_t * ui_rotationbutton2;
lv_obj_t * ui_Panel19;
lv_obj_t * ui_Image18;
lv_obj_t * ui_Label32;
lv_obj_t * ui_Label29;
lv_obj_t * ui_Panel9;
lv_obj_t * ui_Image14;
lv_obj_t * ui_modebutton8;
lv_obj_t * ui_Label34;
lv_obj_t * ui_Panel20;
lv_obj_t * ui_Image19;
lv_obj_t * ui_Label31;
lv_obj_t * ui_Button8;
lv_obj_t * ui_Image20;
lv_obj_t * ui_Button5;
lv_obj_t * ui_Image21;
lv_obj_t * ui_Label33;
lv_obj_t * ui_Label35;

// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
lv_obj_t * ui_Screen5;
lv_obj_t * ui_Panel18;
lv_obj_t * ui_Panel21;
lv_obj_t * ui_Button9;
lv_obj_t * ui_Panel22;
lv_obj_t * ui_Image17;
lv_obj_t * ui_Label36;
lv_obj_t * ui_Label37;
lv_obj_t * ui_Button10;
lv_obj_t * ui_Panel24;
void ui_event_Button11(lv_event_t * e);
lv_obj_t * ui_Button11;
lv_obj_t * ui_Panel25;
lv_obj_t * ui_Image23;
lv_obj_t * ui_Label41;
lv_obj_t * ui_Label38;
lv_obj_t * ui_Label39;
lv_obj_t * ui____initial_actions0;

// SCREEN: ui_Screen6
void ui_Screen6_screen_init(void);
lv_obj_t * ui_Screen6;
void ui_event_wifibutton(lv_event_t * e);
lv_obj_t * ui_wifibutton;
lv_obj_t * ui_Panel26;
lv_obj_t * ui_Image24;
lv_obj_t * ui_Label40;
void ui_event_updatebutton(lv_event_t * e);
lv_obj_t * ui_updatebutton;
lv_obj_t * ui_Label43;
void ui_event_Button12(lv_event_t * e);
lv_obj_t * ui_Button12;
lv_obj_t * ui_Panel27;
lv_obj_t * ui_Image25;
lv_obj_t * ui_Label44;
void ui_event_logbutton(lv_event_t * e);
lv_obj_t * ui_logbutton;
lv_obj_t * ui_Panel28;
lv_obj_t * ui_Label42;
lv_obj_t * ui_Label45;
void ui_event_errorbutton(lv_event_t * e);
lv_obj_t * ui_errorbutton;
lv_obj_t * ui_Panel29;
lv_obj_t * ui_Label48;
lv_obj_t * ui_Label46;
lv_obj_t * ui_Label47;

// SCREEN: ui_Screen7
void ui_Screen7_screen_init(void);
lv_obj_t * ui_Screen7;
lv_obj_t * ui_wifibackpanel;
lv_obj_t * ui_wififfrontpanel;
lv_obj_t * ui_Imagenowifi;
lv_obj_t * ui_wifilabel;
void ui_event_backtosetupbutton(lv_event_t * e);
lv_obj_t * ui_backtosetupbutton;
lv_obj_t * ui_BACKTOSETUPPANEL;
lv_obj_t * ui_imagebackonwifi;
lv_obj_t * ui_BACKTOSETUP;
void ui_event_Switch1(lv_event_t * e);
lv_obj_t * ui_Switch1;
lv_obj_t * ui_offlab;
lv_obj_t * ui_fhewiofiokwef;
lv_obj_t * ui_onlab;
lv_obj_t * ui_Roller1;
lv_obj_t * ui_wifissid;
void ui_event_backtosetupbutton2(lv_event_t * e);
lv_obj_t * ui_backtosetupbutton2;
lv_obj_t * ui_BACKTOSETUP2;
void ui_event_passwordarea(lv_event_t * e);
lv_obj_t * ui_passwordarea;
lv_obj_t * ui_passwordboard;
void ui_event_okbutton(lv_event_t * e);
lv_obj_t * ui_okbutton;
lv_obj_t * ui_oklabel;
lv_obj_t * ui_Checkbox1;
// SCREEN: ui_Screen8
void ui_Screen8_screen_init(void);
lv_obj_t * ui_Screen8;
void ui_event_backcustom(lv_event_t * e);
lv_obj_t * ui_backcustom;
lv_obj_t * ui_backcustomimg;
lv_obj_t * ui_time1button;
lv_obj_t * ui_minsec1;
lv_obj_t * ui_time1;
lv_obj_t * ui_time1button2;
lv_obj_t * ui_minsec3;
lv_obj_t * ui_time3;
lv_obj_t * ui_time1button3;
lv_obj_t * ui_minsec4;
lv_obj_t * ui_time4;
void ui_event_rotationbutton1(lv_event_t * e);
lv_obj_t * ui_rotationbutton1;
lv_obj_t * ui_tipatrykutnik1;
lv_obj_t * ui_rotationdirection1;
lv_obj_t * ui_rotationdirection3;
void ui_event_rotationbutton3(lv_event_t * e);
lv_obj_t * ui_rotationbutton3;
lv_obj_t * ui_tipatrykutnik3;
lv_obj_t * ui_rotationdirection5;
lv_obj_t * ui_rotationdirection2;
void ui_event_rotationbutton4(lv_event_t * e);
lv_obj_t * ui_rotationbutton4;
lv_obj_t * ui_tipatrykutnik4;
lv_obj_t * ui_rotationdirection7;
lv_obj_t * ui_rotationdirection4;
void ui_event_speedbutton1(lv_event_t * e);
lv_obj_t * ui_speedbutton1;
lv_obj_t * ui_rpmlabel;
lv_obj_t * ui_rpmvalue;
void ui_event_speedbutton3(lv_event_t * e);
lv_obj_t * ui_speedbutton3;
lv_obj_t * ui_rpmlabel2;
lv_obj_t * ui_rpmvalue2;
void ui_event_speedbutton4(lv_event_t * e);
lv_obj_t * ui_speedbutton4;
lv_obj_t * ui_rpmlabel3;
lv_obj_t * ui_rpmvalue3;
void ui_event_speedbutton5(lv_event_t * e);
lv_obj_t * ui_speedbutton5;
lv_obj_t * ui_rpmlabel4;
lv_obj_t * ui_rpmvalue4;
// SCREEN: ui_Screen9
void ui_Screen9_screen_init(void);
lv_obj_t * ui_Screen9;
lv_obj_t * ui_Keyboard2;
void ui_event_Button6(lv_event_t * e);
lv_obj_t * ui_Button6;
lv_obj_t * ui_Image8;
lv_obj_t * ui_timevaluemin;
lv_obj_t * ui_minuteslabel;
lv_obj_t * ui_twodotslabel;
lv_obj_t * ui_timevaluemin2;
lv_obj_t * ui_secondslabel;
lv_obj_t * ui____initial_actions0;

const lv_img_dsc_t * ui_imgset_vector[1] = {&ui_img_vector2_png};
const lv_img_dsc_t * ui_imgset_group_[1] = {&ui_img_group_8_png};
const lv_img_dsc_t * ui_imgset_right_line[2] = {&ui_img_right_line1_png, &ui_img_right_line2_png};
const lv_img_dsc_t * ui_imgset_left_line[1] = {&ui_img_left_line1_png,&ui_img_left_line2_png};
const lv_img_dsc_t * ui_imgset_rectangle_[1] = {&ui_img_rectangle_582_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_starstopbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Label1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_Image1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_Label2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_Image2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_Spinner1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_modebutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_modebutton6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_speedchange2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_modebutton5, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_modebutton4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_modebutton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_rotationbutton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_speedchange, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_rotationbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Panel5, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_Label5, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_Label6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_Panel6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_speedchange(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 15, 0, &ui_Screen2_screen_init);
    }
}
void ui_event_modebutton4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_modebutton4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_modebutton7, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_modebutton5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 15, 0, &ui_Screen3_screen_init);
    }
}
void ui_event_speedchange2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 15, 0, &ui_Screen2_screen_init);
    }
}
void ui_event_modebutton6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_FADE_ON, 15, 0, &ui_Screen4_screen_init);
    }
}
void ui_event_customsetupbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen8, LV_SCR_LOAD_ANIM_FADE_ON, 15, 0, &ui_Screen8_screen_init);
    }
}
void ui_event_settingsbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen6, LV_SCR_LOAD_ANIM_FADE_ON, 15, 0, &ui_Screen6_screen_init);
    }
}
void ui_event_modebutton7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_modebutton6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_speedchange2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_modebutton5, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_modebutton4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_modebutton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_rotationbutton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_speedchange, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_modebutton7, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_modebutton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 15, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_TextArea1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_Button3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_modebutton2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_Image8, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_Image4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_Panel10, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_Panel8, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_Panel4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_eventhandler_modebutton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_TextArea1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_Button3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_modebutton2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_Image8, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_Image4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_Panel10, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_Panel8, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_Panel4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_modebutton3(lv_event_t *e);

// void ui_event_Button6(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 15, 0, &ui_Screen1_screen_init);
//     }
// }
void ui_event_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen5, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 15, 0, &ui_Screen5_screen_init);
    }
}
void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 15, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_speedchange3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 15, 0, &ui_Screen2_screen_init);
    }
}
void ui_event_rotationbutton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Panel5, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_Label5, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_Label6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_Panel6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_Button11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_FADE_ON, 15, 0, &ui_Screen4_screen_init);
    }
}
void ui_event_speedbutton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 15, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_speedbutton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 15, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_speedbutton4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 15, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_speedbutton5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 15, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen8, LV_SCR_LOAD_ANIM_FADE_ON, 15, 0, &ui_Screen8_screen_init);
    }
}
///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui_Screen3_screen_init();
    ui_Screen4_screen_init();
    ui_Screen5_screen_init();
    ui_Screen6_screen_init();
    ui_Screen7_screen_init();
    ui_Screen8_screen_init();
    ui_Screen9_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
