// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label107;
extern lv_obj_t * ui_Label108;
void ui_event_starstopbutton(lv_event_t * e);
extern lv_obj_t * ui_starstopbutton;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Spinner1;
void ui_event_modebutton(lv_event_t * e);
extern lv_obj_t * ui_modebutton;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label3;
void ui_event_rotationbutton(lv_event_t * e);
extern lv_obj_t * ui_rotationbutton;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Image6;
void ui_event_speedchange(lv_event_t * e);
extern lv_obj_t * ui_speedchange;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label7;
void ui_event_modebutton4(lv_event_t * e);
extern lv_obj_t * ui_modebutton4;
extern lv_obj_t * ui_Label13;
void ui_event_modebutton5(lv_event_t * e);
extern lv_obj_t * ui_modebutton5;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label55;

void ui_event_modebutton6(lv_event_t * e);
extern lv_obj_t * ui_modebutton6;
extern lv_obj_t * ui_Panelmode;
extern lv_obj_t * ui_Imagemode;
extern lv_obj_t * ui_Label96;
extern lv_obj_t * ui_Label97;
extern lv_obj_t * ui_Label98;
extern lv_obj_t * ui_Label99;
void ui_event_modebutton7(lv_event_t * e);
extern lv_obj_t * ui_modebutton7;
extern lv_obj_t * ui_Label20;
void ui_event_customsetupbutton(lv_event_t * e);
extern lv_obj_t * ui_customsetupbutton;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Panel15;
extern lv_obj_t * ui_Label21;
void ui_event_settingsbutton(lv_event_t * e);
extern lv_obj_t * ui_settingsbutton;
extern lv_obj_t * ui_nasrojochki;
void ui_event_errormesssage1(lv_event_t * e);
extern lv_obj_t * ui_messagePanel1;
extern lv_obj_t * ui_messageLabel1;
extern lv_obj_t * ui_messagebutoon1;
extern lv_obj_t * ui_messagebutoon1label;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Panelline2;
extern lv_obj_t * ui_Panelline3;
extern lv_obj_t * ui_Panelline4;
extern lv_obj_t * ui_Panelline5;
extern lv_obj_t * ui_Panelline6;
extern lv_obj_t * ui_Panelline7;
extern lv_obj_t * ui_Panelline8;
extern lv_obj_t * ui_Panelline9;
extern lv_obj_t * ui_Panelline10;
extern lv_obj_t * ui_Panelline11;
extern lv_obj_t * ui_Panelline12;
extern lv_obj_t * ui_Panelline13;
extern lv_obj_t * ui_Panelline14;
extern lv_obj_t * ui_Panelline15;
extern lv_obj_t * ui_Panelline16;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_modebutton2;
extern lv_obj_t * ui_cleanbutton;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Labelclean;
extern lv_obj_t * ui_eneterbutton;
extern lv_obj_t * ui_enterlabel;
extern lv_obj_t * ui_Buttonleftline;
extern lv_obj_t * ui_Buttonrightline;
extern lv_obj_t * ui_cleanbutton;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Keyboard1;
void ui_eventhandler_modebutton3(lv_event_t * e);
extern lv_obj_t * ui_modebutton3;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui____initial_actions0;
void ui_event_modebutton2(lv_event_t * e);
extern lv_obj_t * ui_modebutton2;
extern lv_obj_t * ui_Label12;
void ui_event_modebutton3(lv_event_t *e);
void ui_event_Buttonrightline(lv_event_t *e);
void ui_event_Buttonleftline(lv_event_t *e);
void ui_event_cleanbutton(lv_event_t *e);
void ui_event_entermode(lv_event_t * e);
void ui_event_confirm_speed(lv_event_t *e);

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_programbutton;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_programbutton2;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_programbutton3;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_programbutton4;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_programbutton5;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_programbutton6;
extern lv_obj_t * ui_Label26;
void ui_event_programbutton(lv_event_t * e);
extern lv_obj_t * ui_programbutton;
extern lv_obj_t * ui_Label18;
void ui_event_programbutton2(lv_event_t * e);
extern lv_obj_t * ui_programbutton2;
extern lv_obj_t * ui_Label22;
void ui_event_programbutton3(lv_event_t * e);
extern lv_obj_t * ui_programbutton3;
extern lv_obj_t * ui_Label23;
void ui_event_programbutton4(lv_event_t * e);
extern lv_obj_t * ui_programbutton4;
extern lv_obj_t * ui_Label24;
void ui_event_programbutton5(lv_event_t * e);
extern lv_obj_t * ui_programbutton5;
extern lv_obj_t * ui_Label25;
void ui_event_programbutton6(lv_event_t * e);
extern lv_obj_t * ui_programbutton6;
extern lv_obj_t * ui_Label26;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_Label21;
// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t * ui_Screen4;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Panel15;
extern lv_obj_t * ui_Image12;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Panel16;
extern lv_obj_t * ui_Image15;
extern lv_obj_t * ui_Label28;
void ui_event_speedchange3(lv_event_t * e);
extern lv_obj_t * ui_speedchange3;
extern lv_obj_t * ui_Panel17;
extern lv_obj_t * ui_Image16;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_Label27;
void ui_event_rotationbutton56(lv_event_t * e);
extern lv_obj_t * ui_rotationbutton56;
extern lv_obj_t * ui_Panel19;
extern lv_obj_t * ui_Image18;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Image14;
extern lv_obj_t * ui_modebutton8;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_Panel20;
extern lv_obj_t * ui_Image19;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Image20;
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Image21;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui_Label105;
extern lv_obj_t * ui_Label106;

void ui_event_Button8(lv_event_t *e);
void ui_event_Button5(lv_event_t *e);
void ui_event_modebutton8(lv_event_t *e);
// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_Panel18;
extern lv_obj_t * ui_Panel21;
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Panel22;
extern lv_obj_t * ui_Image17;
extern lv_obj_t * ui_Label36;
extern lv_obj_t * ui_Label37;
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Panel24;
void ui_event_Button11(lv_event_t * e);
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Panel25;
extern lv_obj_t * ui_Image23;
extern lv_obj_t * ui_Label41;
extern lv_obj_t * ui_Label38;
extern lv_obj_t * ui_Label39;
extern lv_obj_t * ui____initial_actions0;
// SCREEN: ui_Screen6
void ui_Screen6_screen_init(void);
extern lv_obj_t * ui_Screen6;
void ui_event_wifibutton(lv_event_t * e);
extern lv_obj_t * ui_wifibutton;
extern lv_obj_t * ui_Panel26;
extern lv_obj_t * ui_Image24;
extern lv_obj_t * ui_Label40;
void ui_event_updatebutton(lv_event_t * e);
extern lv_obj_t * ui_updatebutton;
extern lv_obj_t * ui_Label43;
void ui_event_Button12(lv_event_t * e);
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_Panel27;
extern lv_obj_t * ui_Image25;
extern lv_obj_t * ui_Label44;
void ui_event_logbutton(lv_event_t * e);
extern lv_obj_t * ui_logbutton;
extern lv_obj_t * ui_Panel28;
extern lv_obj_t * ui_Label42;
extern lv_obj_t * ui_Label45;
void ui_event_errorbutton(lv_event_t * e);
extern lv_obj_t * ui_errorbutton;
extern lv_obj_t * ui_Panel29;
extern lv_obj_t * ui_Label48;
extern lv_obj_t * ui_Label46;
extern lv_obj_t * ui_Label47;
// SCREEN: ui_Screen7
void ui_Screen7_screen_init(void);
extern lv_obj_t * ui_Screen7;
extern lv_obj_t * ui_wifibackpanel;
extern lv_obj_t * ui_wififfrontpanel;
extern lv_obj_t * ui_Imagenowifi;
extern lv_obj_t * ui_wifilabel;
void ui_event_backtosetupbutton(lv_event_t * e);
extern lv_obj_t * ui_backtosetupbutton;
extern lv_obj_t * ui_BACKTOSETUPPANEL;
extern lv_obj_t * ui_imagebackonwifi;
extern lv_obj_t * ui_BACKTOSETUP;
void ui_event_Switch1(lv_event_t * e);
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_offlab;
extern lv_obj_t * ui_fhewiofiokwef;
extern lv_obj_t * ui_onlab;
extern lv_obj_t * ui_Roller1;
extern lv_obj_t * ui_wifissid;
void event_enterwifi_button(lv_event_t * e);
extern lv_obj_t * ui_backtosetupbutton2;
extern lv_obj_t * ui_BACKTOSETUP2;
void ui_event_passwordarea(lv_event_t * e);
extern lv_obj_t * ui_passwordarea;
extern lv_obj_t * ui_passwordboard;
void ui_event_okbutton(lv_event_t * e);
extern lv_obj_t * ui_okbutton;
extern lv_obj_t * ui_oklabel;
extern lv_obj_t * ui_Checkbox1;
// SCREEN: ui_Screen8
void ui_Screen8_screen_init(void);
extern lv_obj_t * ui_Screen8;
void ui_event_backcustom(lv_event_t * e);
extern lv_obj_t * ui_backcustom;
extern lv_obj_t * ui_backcustomimg;
extern lv_obj_t * ui_time1button;
extern lv_obj_t * ui_minsec1;
extern lv_obj_t * ui_time1;
extern lv_obj_t * ui_time1button2;
extern lv_obj_t * ui_minsec3;
extern lv_obj_t * ui_time3;
extern lv_obj_t * ui_time1button3;
extern lv_obj_t * ui_minsec4;
extern lv_obj_t * ui_time4;
void ui_event_rotationbutton1(lv_event_t * e);
extern lv_obj_t * ui_rotationbutton1;
extern lv_obj_t * ui_tipatrykutnik1;
extern lv_obj_t * ui_rotationdirection1;
extern lv_obj_t * ui_rotationdirection3;
void ui_event_rotationbutton3(lv_event_t * e);
extern lv_obj_t * ui_rotationbutton3;
extern lv_obj_t * ui_tipatrykutnik3;
extern lv_obj_t * ui_rotationdirection5;
extern lv_obj_t * ui_rotationdirection2;
void ui_event_rotationbutton4(lv_event_t * e);
extern lv_obj_t * ui_rotationbutton4;
extern lv_obj_t * ui_tipatrykutnik4;
extern lv_obj_t * ui_rotationdirection7;
extern lv_obj_t * ui_rotationdirection4;
void ui_event_speedbutton1(lv_event_t * e);
extern lv_obj_t * ui_speedbutton1;
extern lv_obj_t * ui_rpmlabel;
extern lv_obj_t * ui_rpmvalue;
void ui_event_speedbutton3(lv_event_t * e);
extern lv_obj_t * ui_speedbutton3;
extern lv_obj_t * ui_rpmlabel2;
extern lv_obj_t * ui_rpmvalue2;
void ui_event_speedbutton4(lv_event_t * e);
extern lv_obj_t * ui_speedbutton4;
extern lv_obj_t * ui_rpmlabel3;
extern lv_obj_t * ui_rpmvalue3;
void ui_event_speedbutton5(lv_event_t * e);
extern lv_obj_t * ui_speedbutton5;
extern lv_obj_t * ui_rpmlabel4;
extern lv_obj_t * ui_rpmvalue4;
void ui_event_speedset(lv_event_t *e);
// SCREEN: ui_Screen9
void ui_Screen9_screen_init(void);
extern lv_obj_t * ui_Screen9;
extern lv_obj_t * ui_minuteslabel;
extern lv_obj_t * ui_secondslabel;
extern lv_obj_t * ui_rollerminutes;
extern lv_obj_t * ui_rollerseconds;
void ui_event_setuptimebutton(lv_event_t * e);
extern lv_obj_t * ui_setuptimebutton;
extern lv_obj_t * ui_BACKTOSETUP3;
extern lv_obj_t * ui____initial_actions0;
void ui_event_timeset(lv_event_t * e);
void ui_event_confirm_time(lv_event_t * e);
//SCREEN: ui_screen10
void ui_Screen10_screen_init(void);
extern lv_obj_t * ui_Screen10;
extern lv_obj_t * ui_rollerseconds2;
extern lv_obj_t * ui_secondslabel2;
extern lv_obj_t * ui_minuteslabel2;
extern lv_obj_t * ui_rollerminutes2;
void ui_event_setuptimebutton2(lv_event_t * e);
extern lv_obj_t * ui_BACKTOSETUP4;
extern lv_obj_t * ui_setuptimebutton2;

LV_IMG_DECLARE(ui_img_vector_png);    // assets/Vector.png
LV_IMG_DECLARE(ui_img_vector2_png);    // assets/Vector2.png
LV_IMG_DECLARE(ui_img_group_8_png);    // assets/Group 8.png
LV_IMG_DECLARE(ui_img_left_line1_png);    // assets/Left_Line1.png
LV_IMG_DECLARE(ui_img_right_line1_png);    // assets/right_line1.png
LV_IMG_DECLARE(ui_img_speed_png);    // assets/speed.png
LV_IMG_DECLARE(ui_img_clock_png);    // assets/clock.png
LV_IMG_DECLARE(ui_img_right_line2_png);    // assets/right_line2.png
LV_IMG_DECLARE(ui_img_left_line2_png);    // assets/left_line2.png
LV_IMG_DECLARE(ui_img_enter_line_png);    // assets/enter_line.png
LV_IMG_DECLARE(ui_img_back_png);    // assets/back.png
LV_IMG_DECLARE(ui_img_settinggroup_png);    // assets/settinggroup.png
LV_IMG_DECLARE(ui_img_galochka_png);    // assets/galochka.png
LV_IMG_DECLARE(ui_img_1502005807);    // assets/ion_options-outline.png
LV_IMG_DECLARE(ui_img_wifi_png);    // assets/wifi.png
LV_IMG_DECLARE(ui_img_back_png);    // assets/back.png
LV_IMG_DECLARE(ui_img_nowifi_png);    // assets/nowifi.png
LV_IMG_DECLARE(ui_img_rectangle_582_png);    // assets/Rectangle 582.png
LV_IMG_DECLARE(ui_img_169476923);    // assets/Rectangle 582 (1).png
LV_IMG_DECLARE(ui_img_169479996);    // assets/Rectangle 582 (2).png








void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
