// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Panel2;
void ui_event_starstopbutton(lv_event_t * e);
extern lv_obj_t * ui_starstopbutton;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Spinner1;
void ui_event_modebutton(lv_event_t * e);
extern lv_obj_t * ui_modebutton;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label3;
void ui_event_rotationbutton(lv_event_t * e);
extern lv_obj_t * ui_rotationbutton;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Image6;
void ui_event_speedchange(lv_event_t * e);
extern lv_obj_t * ui_speedchange;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label7;
void ui_event_modebutton4(lv_event_t * e);
extern lv_obj_t * ui_modebutton4;
extern lv_obj_t * ui_Label13;
void ui_event_modebutton5(lv_event_t * e);
extern lv_obj_t * ui_modebutton5;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Label11;
void ui_event_speedchange2(lv_event_t * e);
extern lv_obj_t * ui_speedchange2;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label15;
void ui_event_modebutton6(lv_event_t * e);
extern lv_obj_t * ui_modebutton6;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Label16;
void ui_event_modebutton7(lv_event_t * e);
extern lv_obj_t * ui_modebutton7;
extern lv_obj_t * ui_Label20;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Panelline2;
extern lv_obj_t * ui_Panelline3;
extern lv_obj_t * ui_Panelline4;
extern lv_obj_t * ui_Panelline5;
extern lv_obj_t * ui_Panelline6;
extern lv_obj_t * ui_Panelline7;
extern lv_obj_t * ui_Panelline8;
extern lv_obj_t * ui_Panelline9;
extern lv_obj_t * ui_Panelline10;
extern lv_obj_t * ui_Panelline11;
extern lv_obj_t * ui_Panelline12;
extern lv_obj_t * ui_Panelline13;
extern lv_obj_t * ui_Panelline14;
extern lv_obj_t * ui_Panelline15;
extern lv_obj_t * ui_Panelline16;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_modebutton2;
extern lv_obj_t * ui_cleanbutton;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Labelclean;
extern lv_obj_t * ui_eneterbutton;
extern lv_obj_t * ui_enterlabel;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Keyboard1;
void ui_eventhandler_modebutton3(lv_event_t * e);
extern lv_obj_t * ui_modebutton3;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui____initial_actions0;
void ui_event_modebutton2(lv_event_t * e);
extern lv_obj_t * ui_modebutton2;
extern lv_obj_t * ui_Label12;
void ui_event_modebutton3(lv_event_t *e);
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_programbutton;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_programbutton2;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_programbutton3;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_programbutton4;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_programbutton5;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_programbutton6;
extern lv_obj_t * ui_Label26;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_Label21;
// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t * ui_Screen4;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Panel15;
extern lv_obj_t * ui_Image12;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Panel16;
extern lv_obj_t * ui_Image15;
extern lv_obj_t * ui_Label28;
void ui_event_speedchange3(lv_event_t * e);
extern lv_obj_t * ui_speedchange3;
extern lv_obj_t * ui_Panel17;
extern lv_obj_t * ui_Image16;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_Label27;
void ui_event_rotationbutton2(lv_event_t * e);
extern lv_obj_t * ui_rotationbutton2;
extern lv_obj_t * ui_Panel19;
extern lv_obj_t * ui_Image18;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Image14;
extern lv_obj_t * ui_modebutton8;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_Panel20;
extern lv_obj_t * ui_Image19;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Image20;
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Image21;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_Label35;
// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_Panel18;
extern lv_obj_t * ui_Panel21;
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Panel22;
extern lv_obj_t * ui_Image17;
extern lv_obj_t * ui_Label36;
extern lv_obj_t * ui_Label37;
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Panel24;
void ui_event_Button11(lv_event_t * e);
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Panel25;
extern lv_obj_t * ui_Image23;
extern lv_obj_t * ui_Label41;
extern lv_obj_t * ui_Label38;
extern lv_obj_t * ui_Label39;
extern lv_obj_t * ui____initial_actions0;



LV_IMG_DECLARE(ui_img_vector_png);    // assets/Vector.png
LV_IMG_DECLARE(ui_img_vector2_png);    // assets/Vector2.png
LV_IMG_DECLARE(ui_img_group_8_png);    // assets/Group 8.png
LV_IMG_DECLARE(ui_img_left_line1_png);    // assets/Left_Line1.png
LV_IMG_DECLARE(ui_img_right_line1_png);    // assets/right_line1.png
LV_IMG_DECLARE(ui_img_speed_png);    // assets/speed.png
LV_IMG_DECLARE(ui_img_clock_png);    // assets/clock.png
LV_IMG_DECLARE(ui_img_right_line2_png);    // assets/right_line2.png
LV_IMG_DECLARE(ui_img_left_line2_png);    // assets/left_line2.png
LV_IMG_DECLARE(ui_img_enter_line_png);    // assets/enter_line.png
LV_IMG_DECLARE(ui_img_back_png);    // assets/back.png
LV_IMG_DECLARE(ui_img_settinggroup_png);    // assets/settinggroup.png
LV_IMG_DECLARE(ui_img_galochka_png);    // assets/galochka.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
