// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen7_screen_init(void)
{
    ui_Screen7 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen7, lv_color_hex(0x202429), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifibackpanel = lv_obj_create(ui_Screen7);
    lv_obj_set_width(ui_wifibackpanel, 768);
    lv_obj_set_height(ui_wifibackpanel, 448);
    lv_obj_set_align(ui_wifibackpanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_wifibackpanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_wifibackpanel, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_wifibackpanel, lv_color_hex(0x8690AB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifibackpanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_wifibackpanel, lv_color_hex(0x363A45), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_wifibackpanel, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wififfrontpanel = lv_obj_create(ui_wifibackpanel);
    lv_obj_set_width(ui_wififfrontpanel, 740);
    lv_obj_set_height(ui_wififfrontpanel, 419);
    lv_obj_set_x(ui_wififfrontpanel, 0);
    lv_obj_set_y(ui_wififfrontpanel, -2);
    lv_obj_set_align(ui_wififfrontpanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_wififfrontpanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_wififfrontpanel, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_wififfrontpanel, lv_color_hex(0x313841), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wififfrontpanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_wififfrontpanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_wififfrontpanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_wififfrontpanel, lv_color_hex(0x313841), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wififfrontpanel, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Imagenowifi = lv_img_create(ui_wififfrontpanel);
    lv_img_set_src(ui_Imagenowifi, &ui_img_nowifi_png);
    lv_obj_set_width(ui_Imagenowifi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Imagenowifi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Imagenowifi, -310);
    lv_obj_set_y(ui_Imagenowifi, -158);
    lv_obj_set_align(ui_Imagenowifi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Imagenowifi, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Imagenowifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wifilabel = lv_label_create(ui_wififfrontpanel);
    lv_obj_set_width(ui_wifilabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifilabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifilabel, -203);
    lv_obj_set_y(ui_wifilabel, -160);
    lv_obj_set_align(ui_wifilabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wifilabel, "WI-FI");
    lv_obj_set_style_text_color(ui_wifilabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wifilabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_wifilabel, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backtosetupbutton = lv_btn_create(ui_wififfrontpanel);
    lv_obj_set_width(ui_backtosetupbutton, 354);
    lv_obj_set_height(ui_backtosetupbutton, 132);
    lv_obj_set_x(ui_backtosetupbutton, -179);
    lv_obj_set_y(ui_backtosetupbutton, 132);
    lv_obj_set_align(ui_backtosetupbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backtosetupbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_backtosetupbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_backtosetupbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_backtosetupbutton, lv_color_hex(0x313841), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backtosetupbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_backtosetupbutton, lv_color_hex(0xDF312A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_backtosetupbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_backtosetupbutton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BACKTOSETUPPANEL = lv_obj_create(ui_backtosetupbutton);
    lv_obj_set_width(ui_BACKTOSETUPPANEL, 143);
    lv_obj_set_height(ui_BACKTOSETUPPANEL, 116);
    lv_obj_set_x(ui_BACKTOSETUPPANEL, -95);
    lv_obj_set_y(ui_BACKTOSETUPPANEL, -1);
    lv_obj_set_align(ui_BACKTOSETUPPANEL, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BACKTOSETUPPANEL, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BACKTOSETUPPANEL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BACKTOSETUPPANEL, lv_color_hex(0x8690AB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BACKTOSETUPPANEL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_BACKTOSETUPPANEL, lv_color_hex(0x363A45), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_BACKTOSETUPPANEL, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BACKTOSETUPPANEL, lv_color_hex(0x363A45), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BACKTOSETUPPANEL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imagebackonwifi = lv_img_create(ui_BACKTOSETUPPANEL);
    lv_img_set_src(ui_imagebackonwifi, &ui_img_back_png);
    lv_obj_set_width(ui_imagebackonwifi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imagebackonwifi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imagebackonwifi, -9);
    lv_obj_set_y(ui_imagebackonwifi, 1);
    lv_obj_set_align(ui_imagebackonwifi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imagebackonwifi, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imagebackonwifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BACKTOSETUP = lv_label_create(ui_backtosetupbutton);
    lv_obj_set_width(ui_BACKTOSETUP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BACKTOSETUP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BACKTOSETUP, 54);
    lv_obj_set_y(ui_BACKTOSETUP, -2);
    lv_obj_set_align(ui_BACKTOSETUP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BACKTOSETUP, "BACK");
    lv_obj_set_style_text_font(ui_BACKTOSETUP, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch1 = lv_switch_create(ui_wififfrontpanel);
    lv_obj_set_width(ui_Switch1, 143);
    lv_obj_set_height(ui_Switch1, 70);
    lv_obj_set_x(ui_Switch1, 264);
    lv_obj_set_y(ui_Switch1, -155);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch1, lv_color_hex(0x313841), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Switch1, lv_color_hex(0xDF312A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Switch1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Switch1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_offlab = lv_label_create(ui_Switch1);
    lv_obj_set_width(ui_offlab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_offlab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_offlab, 27);
    lv_obj_set_y(ui_offlab, -2);
    lv_obj_set_align(ui_offlab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_offlab, "off");
    lv_obj_set_style_text_color(ui_offlab, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_offlab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_offlab, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fhewiofiokwef = lv_obj_create(ui_Switch1);
    lv_obj_set_width(ui_fhewiofiokwef, 63);
    lv_obj_set_height(ui_fhewiofiokwef, 63);
    lv_obj_set_x(ui_fhewiofiokwef, 37);
    lv_obj_set_y(ui_fhewiofiokwef, -1);
    lv_obj_set_align(ui_fhewiofiokwef, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_fhewiofiokwef, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_fhewiofiokwef, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_fhewiofiokwef, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_fhewiofiokwef, lv_color_hex(0xDF312A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fhewiofiokwef, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_fhewiofiokwef, lv_color_hex(0xDF312A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_fhewiofiokwef, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_fhewiofiokwef, lv_color_hex(0x313841), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_fhewiofiokwef, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_onlab = lv_label_create(ui_Switch1);
    lv_obj_set_width(ui_onlab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_onlab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_onlab, -32);
    lv_obj_set_y(ui_onlab, -2);
    lv_obj_set_align(ui_onlab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_onlab, "on");
    lv_obj_add_flag(ui_onlab, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_onlab, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_onlab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_onlab, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Roller1 = lv_roller_create(ui_wififfrontpanel);
    lv_roller_set_options(ui_Roller1, "Option 1\nOption 2\nOption 3", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_Roller1, 135);
    lv_obj_set_height(ui_Roller1, 145);
    lv_obj_set_x(ui_Roller1, -253);
    lv_obj_set_y(ui_Roller1, -32);
    lv_obj_set_align(ui_Roller1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Roller1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_Roller1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Roller1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Roller1, lv_color_hex(0x313841), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Roller1, lv_color_hex(0xDF312A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Roller1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Roller1, lv_color_hex(0xDF312A), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller1, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_wifissid = lv_label_create(ui_wififfrontpanel);
    lv_obj_set_width(ui_wifissid, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifissid, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifissid, 10);
    lv_obj_set_y(ui_wifissid, -162);
    lv_obj_set_align(ui_wifissid, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wifissid, "WI-FI SSID");
    lv_obj_add_flag(ui_wifissid, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_wifissid, lv_color_hex(0xE4322E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wifissid, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_wifissid, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backtosetupbutton2 = lv_btn_create(ui_wififfrontpanel);
    lv_obj_set_width(ui_backtosetupbutton2, 354);
    lv_obj_set_height(ui_backtosetupbutton2, 132);
    lv_obj_set_x(ui_backtosetupbutton2, 183);
    lv_obj_set_y(ui_backtosetupbutton2, 131);
    lv_obj_set_align(ui_backtosetupbutton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backtosetupbutton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_backtosetupbutton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_backtosetupbutton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_backtosetupbutton2, lv_color_hex(0x313841), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backtosetupbutton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_backtosetupbutton2, lv_color_hex(0xDF312A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_backtosetupbutton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_backtosetupbutton2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BACKTOSETUP2 = lv_label_create(ui_backtosetupbutton2);
    lv_obj_set_width(ui_BACKTOSETUP2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BACKTOSETUP2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BACKTOSETUP2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BACKTOSETUP2, "ENTER");
    lv_obj_set_style_text_font(ui_BACKTOSETUP2, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_passwordarea = lv_textarea_create(ui_Screen7);
    lv_obj_set_width(ui_passwordarea, 374);
    lv_obj_set_height(ui_passwordarea, LV_SIZE_CONTENT);    /// 160
    lv_obj_set_x(ui_passwordarea, 15);
    lv_obj_set_y(ui_passwordarea, -112);
    lv_obj_set_align(ui_passwordarea, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_passwordarea, "Password");
    lv_textarea_set_one_line(ui_passwordarea, true);
    lv_obj_add_flag(ui_passwordarea, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_radius(ui_passwordarea, 40, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_passwordboard = lv_keyboard_create(ui_Screen7);
    lv_obj_set_width(ui_passwordboard, 732);
    lv_obj_set_height(ui_passwordboard, 286);
    lv_obj_set_x(ui_passwordboard, 2);
    lv_obj_set_y(ui_passwordboard, 60);
    lv_obj_set_align(ui_passwordboard, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_passwordboard, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_radius(ui_passwordboard, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_passwordboard, lv_color_hex(0x313841), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_passwordboard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_passwordboard, &lv_font_montserrat_32, LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_okbutton = lv_btn_create(ui_passwordboard);
    lv_obj_set_width(ui_okbutton, 100);
    lv_obj_set_height(ui_okbutton, 59);
    lv_obj_set_x(ui_okbutton, 306);
    lv_obj_set_y(ui_okbutton, 102);
    lv_obj_set_align(ui_okbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_okbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_okbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_okbutton, lv_color_hex(0x202429), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_okbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_okbutton, lv_color_hex(0xE63029), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_okbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_okbutton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_oklabel = lv_label_create(ui_okbutton);
    lv_obj_set_width(ui_oklabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_oklabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_oklabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_oklabel, "Enter");
    lv_obj_set_style_text_font(ui_oklabel, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Checkbox1 = lv_checkbox_create(ui_Screen7);
    lv_checkbox_set_text(ui_Checkbox1, "         save wi-fi password");
    lv_obj_set_width(ui_Checkbox1, 438);
    lv_obj_set_height(ui_Checkbox1, 54);
    lv_obj_set_x(ui_Checkbox1, 86);
    lv_obj_set_y(ui_Checkbox1, -35);
    lv_obj_set_align(ui_Checkbox1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Checkbox1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_Checkbox1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Checkbox1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_backtosetupbutton, ui_event_backtosetupbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch1, ui_event_Switch1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_backtosetupbutton2,event_enterwifi_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_passwordarea, ui_event_passwordarea, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_passwordboard, ui_passwordarea);
    lv_obj_add_event_cb(ui_okbutton, ui_event_okbutton, LV_EVENT_ALL, NULL);

}
