// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x26272C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel4, 750);
    lv_obj_set_height(ui_Panel4, 161);
    lv_obj_set_x(ui_Panel4, 0);
    lv_obj_set_y(ui_Panel4, -152);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x8E9BBA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel4, lv_color_hex(0x4F545F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Panel4, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_btn_create(ui_Panel4);
    lv_obj_set_width(ui_Button2, 703);
    lv_obj_set_height(ui_Button2, 128);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x363A45), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -279);
    lv_obj_set_y(ui_Label8, -3);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "MIN\n  10");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 279);
    lv_obj_set_y(ui_Label10, -4);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "MAX\n   10");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel8 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_Panel8, 16);
    lv_obj_set_height(ui_Panel8, 100);
    lv_obj_set_x(ui_Panel8, 167);
    lv_obj_set_y(ui_Panel8, 0);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0x26272C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel8, lv_color_hex(0x363A45), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panelline2 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_Panelline2, 16);
    lv_obj_set_height(ui_Panelline2, 94);
    lv_obj_set_x(ui_Panelline2, 144.59);
    lv_obj_set_y(ui_Panelline2, 2.6);
    lv_obj_set_align(ui_Panelline2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panelline2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panelline2, lv_color_hex(0x26272C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panelline2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panelline2, lv_color_hex(0x363A45), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panelline2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panelline3 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_Panelline3, 16);
    lv_obj_set_height(ui_Panelline3, 88);
    lv_obj_set_x(ui_Panelline3, 122.19);
    lv_obj_set_y(ui_Panelline3, 5.33);
    lv_obj_set_align(ui_Panelline3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panelline3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panelline3, lv_color_hex(0x26272C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panelline3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panelline3, lv_color_hex(0x363A45), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panelline3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panelline4 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_Panelline4, 16);
    lv_obj_set_height(ui_Panelline4, 82);
    lv_obj_set_x(ui_Panelline4, 99.79);
    lv_obj_set_y(ui_Panelline4, 8);
    lv_obj_set_align(ui_Panelline4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panelline4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panelline4, lv_color_hex(0x26272C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panelline4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panelline4, lv_color_hex(0x363A45), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panelline4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panelline5 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_Panelline5, 16);
    lv_obj_set_height(ui_Panelline5, 76);
    lv_obj_set_x(ui_Panelline5, 77.39);
    lv_obj_set_y(ui_Panelline5, 10.66);
    lv_obj_set_align(ui_Panelline5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panelline5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panelline5, lv_color_hex(0x26272C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panelline5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panelline5, lv_color_hex(0x363A45), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panelline5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panelline6 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_Panelline6, 16);
    lv_obj_set_height(ui_Panelline6, 70);
    lv_obj_set_x(ui_Panelline6, 55);
    lv_obj_set_y(ui_Panelline6, 13.3);
    lv_obj_set_align(ui_Panelline6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panelline6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panelline6, lv_color_hex(0x26272C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panelline6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panelline6, lv_color_hex(0x363A45), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panelline6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panelline7 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_Panelline7, 16);
    lv_obj_set_height(ui_Panelline7, 64);
    lv_obj_set_x(ui_Panelline7, 32.59);
    lv_obj_set_y(ui_Panelline7, 16);
    lv_obj_set_align(ui_Panelline7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panelline7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panelline7, lv_color_hex(0x26272C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panelline7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panelline7, lv_color_hex(0x363A45), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panelline7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panelline8 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_Panelline8, 16);
    lv_obj_set_height(ui_Panelline8, 58);
    lv_obj_set_x(ui_Panelline8, 10.19);
    lv_obj_set_y(ui_Panelline8, 18.6);
    lv_obj_set_align(ui_Panelline8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panelline8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panelline8, lv_color_hex(0x26272C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panelline8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panelline8, lv_color_hex(0x363A45), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panelline8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panelline9 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_Panelline9, 16);
    lv_obj_set_height(ui_Panelline9, 52);
    lv_obj_set_x(ui_Panelline9, -12.2);
    lv_obj_set_y(ui_Panelline9, 21.3);
    lv_obj_set_align(ui_Panelline9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panelline9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panelline9, lv_color_hex(0x26272C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panelline9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panelline9, lv_color_hex(0x363A45), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panelline9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Panelline10 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_Panelline10, 16);
    lv_obj_set_height(ui_Panelline10, 46);
    lv_obj_set_x(ui_Panelline10, -34.6);
    lv_obj_set_y(ui_Panelline10, 24);
    lv_obj_set_align(ui_Panelline10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panelline10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panelline10, lv_color_hex(0x26272C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panelline10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panelline10, lv_color_hex(0x363A45), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panelline10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Panelline11 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_Panelline11, 16);
    lv_obj_set_height(ui_Panelline11, 40);
    lv_obj_set_x(ui_Panelline11, -57);
    lv_obj_set_y(ui_Panelline11, 26.6);
    lv_obj_set_align(ui_Panelline11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panelline11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panelline11, lv_color_hex(0x26272C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panelline11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panelline11, lv_color_hex(0x363A45), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panelline11, 255, LV_PART_MAIN | LV_STATE_DEFAULT); 

    ui_Panelline12 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_Panelline12, 16);
    lv_obj_set_height(ui_Panelline12, 34);
    lv_obj_set_x(ui_Panelline12, -79);
    lv_obj_set_y(ui_Panelline12, 29.3);
    lv_obj_set_align(ui_Panelline12, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panelline12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panelline12, lv_color_hex(0x26272C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panelline12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panelline12, lv_color_hex(0x363A45), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panelline12, 255, LV_PART_MAIN | LV_STATE_DEFAULT); 

    ui_Panelline13 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_Panelline13, 16);
    lv_obj_set_height(ui_Panelline13, 28);
    lv_obj_set_x(ui_Panelline13, -101.8);
    lv_obj_set_y(ui_Panelline13, 32);
    lv_obj_set_align(ui_Panelline13, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panelline13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panelline13, lv_color_hex(0x26272C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panelline13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panelline13, lv_color_hex(0x363A45), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panelline13, 255, LV_PART_MAIN | LV_STATE_DEFAULT); 

    ui_Panelline14 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_Panelline14, 16);
    lv_obj_set_height(ui_Panelline14, 22);
    lv_obj_set_x(ui_Panelline14, -124.2);
    lv_obj_set_y(ui_Panelline14, 34.6);
    lv_obj_set_align(ui_Panelline14, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panelline14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panelline14, lv_color_hex(0x26272C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panelline14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panelline14, lv_color_hex(0x363A45), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panelline14, 255, LV_PART_MAIN | LV_STATE_DEFAULT); 

    ui_Panelline15 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_Panelline15, 16);
    lv_obj_set_height(ui_Panelline15, 16);
    lv_obj_set_x(ui_Panelline15, -146.6);
    lv_obj_set_y(ui_Panelline15, 37.3);
    lv_obj_set_align(ui_Panelline15, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panelline15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panelline15, lv_color_hex(0x26272C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panelline15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panelline15, lv_color_hex(0x363A45), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panelline15, 255, LV_PART_MAIN | LV_STATE_DEFAULT); 


    ui_Panel10 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_Panel10, 16);
    lv_obj_set_height(ui_Panel10, 10);
    lv_obj_set_x(ui_Panel10, -169);
    lv_obj_set_y(ui_Panel10, 40);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel10, lv_color_hex(0xE4322E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel10, lv_color_hex(0x363A45), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Buttonrightline = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Buttonrightline, 111);
    lv_obj_set_height(ui_Buttonrightline, 105);
    lv_obj_set_x(ui_Buttonrightline, 164);
    lv_obj_set_y(ui_Buttonrightline, 18);
    lv_obj_set_align(ui_Buttonrightline, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Buttonrightline, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buttonrightline, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Buttonrightline, lv_color_hex(0x202429), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Buttonrightline, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Buttonrightline, lv_color_hex(0x202429), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Buttonrightline, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Buttonrightline, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Buttonrightline, lv_color_hex(0x202429), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Buttonrightline, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_img_create(ui_Buttonrightline);
    lv_img_set_src(ui_Image4, &ui_img_right_line2_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image4, 0);
    lv_obj_set_y(ui_Image4, 0);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Buttonleftline = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Buttonleftline, 111);
    lv_obj_set_height(ui_Buttonleftline, 105);
    lv_obj_set_x(ui_Buttonleftline, -169);
    lv_obj_set_y(ui_Buttonleftline, 15);
    lv_obj_set_align(ui_Buttonleftline, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Buttonleftline, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buttonleftline, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Buttonleftline, lv_color_hex(0x202429), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Buttonleftline, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Buttonleftline, lv_color_hex(0x202429), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Buttonleftline, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Buttonleftline, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Buttonleftline, lv_color_hex(0x202429), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Buttonleftline, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image8 = lv_img_create(ui_Buttonleftline);
    lv_img_set_src(ui_Image8, &ui_img_left_line2_png);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image8, 0);
    lv_obj_set_y(ui_Image8, 0);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_modebutton2 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_modebutton2, 248);
    lv_obj_set_height(ui_modebutton2, 132);
    lv_obj_set_x(ui_modebutton2, -254);
    lv_obj_set_y(ui_modebutton2, 159);
    lv_obj_set_align(ui_modebutton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_modebutton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_modebutton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_modebutton2, 2500, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_modebutton2, lv_color_hex(0x363A45), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_modebutton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_modebutton2, lv_color_hex(0xE4322E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_modebutton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_modebutton2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_modebutton2, lv_color_hex(0x666D82), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_modebutton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_modebutton2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_modebutton2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_modebutton2);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 6);
    lv_obj_set_y(ui_Label12, -1);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Exit");
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_cleanbutton = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_cleanbutton, 248);
    lv_obj_set_height(ui_cleanbutton, 132);
    lv_obj_set_x(ui_cleanbutton, 5);
    lv_obj_set_y(ui_cleanbutton, 161);
    lv_obj_set_align(ui_cleanbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_cleanbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_cleanbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_cleanbutton, 2500, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cleanbutton, lv_color_hex(0x363A45), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cleanbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cleanbutton, lv_color_hex(0xE4322E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cleanbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cleanbutton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_cleanbutton, lv_color_hex(0x666D82), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_cleanbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_cleanbutton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_cleanbutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelclean = lv_label_create(ui_cleanbutton);
    lv_obj_set_width(ui_Labelclean, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelclean, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelclean, 6);
    lv_obj_set_y(ui_Labelclean, -1);
    lv_obj_set_align(ui_Labelclean, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelclean, "Clean");
    lv_obj_set_style_text_font(ui_Labelclean, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_eneterbutton = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_eneterbutton, 248);
    lv_obj_set_height(ui_eneterbutton, 132);
    lv_obj_set_x(ui_eneterbutton, 263);
    lv_obj_set_y(ui_eneterbutton, 161);
    lv_obj_set_align(ui_eneterbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_eneterbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_eneterbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_eneterbutton, 2500, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_eneterbutton, lv_color_hex(0x363A45), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_eneterbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_eneterbutton, lv_color_hex(0xE4322E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_eneterbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_eneterbutton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_eneterbutton, lv_color_hex(0x666D82), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_eneterbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_eneterbutton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_eneterbutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_enterlabel = lv_label_create(ui_eneterbutton);
    lv_obj_set_width(ui_enterlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_enterlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_enterlabel, 6);
    lv_obj_set_y(ui_enterlabel, -1);
    lv_obj_set_align(ui_enterlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_enterlabel, "Enter");
    lv_obj_set_style_text_font(ui_enterlabel, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button3, 137);
    lv_obj_set_height(ui_Button3, 142);
    lv_obj_set_x(ui_Button3, -3);
    lv_obj_set_y(ui_Button3, 15);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button3, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x363A45), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button3, lv_color_hex(0xE4322E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label9, 67);
    lv_obj_set_height(ui_Label9, 57);
    lv_obj_set_x(ui_Label9, 4);
    lv_obj_set_y(ui_Label9, 3);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "10");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xE4322E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_Screen2);
    lv_keyboard_set_mode(ui_Keyboard1, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_Keyboard1, 806);
    lv_obj_set_height(ui_Keyboard1, 315);
    lv_obj_set_x(ui_Keyboard1, 0);
    lv_obj_set_y(ui_Keyboard1, 77);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_bg_color(ui_Keyboard1, lv_color_hex(0x26272C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Keyboard1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Keyboard1, lv_color_hex(0x363A45), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Keyboard1, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Keyboard1, lv_color_hex(0xE4322E), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Keyboard1, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Keyboard1, &lv_font_montserrat_32, LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_modebutton3 = lv_btn_create(ui_Keyboard1);
    lv_obj_set_width(ui_modebutton3, 315);
    lv_obj_set_height(ui_modebutton3, 142);
    lv_obj_set_x(ui_modebutton3, 241);
    lv_obj_set_y(ui_modebutton3, -77);
    lv_obj_set_align(ui_modebutton3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_modebutton3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_modebutton3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_modebutton3, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_modebutton3, lv_color_hex(0x363A45), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_modebutton3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_modebutton3, lv_color_hex(0xE4322E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_modebutton3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_modebutton3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_modebutton3, lv_color_hex(0x666D82), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_modebutton3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_modebutton3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_modebutton3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image9 = lv_img_create(ui_modebutton3);
    lv_img_set_src(ui_Image9, &ui_img_enter_line_png);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TextArea1 = lv_textarea_create(ui_Screen2);
    lv_obj_set_width(ui_TextArea1, 150);
    lv_obj_set_height(ui_TextArea1, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_TextArea1, -10);
    lv_obj_set_y(ui_TextArea1, -156);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextArea1, 2);
    lv_textarea_set_placeholder_text(ui_TextArea1, "10");
    lv_textarea_set_one_line(ui_TextArea1, true);
    lv_obj_add_flag(ui_TextArea1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_TextArea1, lv_color_hex(0xE4322E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextArea1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextArea1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextArea1, lv_color_hex(0x363A45), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TextArea1, lv_color_hex(0x363A45), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TextArea1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
lv_keyboard_set_textarea(ui_Keyboard1, ui_TextArea1);
lv_obj_add_event_cb(ui_modebutton3, ui_eventhandler_modebutton3, LV_EVENT_CLICKED, NULL); // Use only one relevant callback
lv_obj_add_event_cb(ui_modebutton3, ui_event_modebutton3, LV_EVENT_CLICKED, NULL);
lv_obj_add_event_cb(ui_modebutton2, ui_event_modebutton2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Buttonrightline, ui_event_Buttonrightline, LV_EVENT_CLICKED, NULL);
lv_obj_add_event_cb(ui_Buttonleftline, ui_event_Buttonleftline, LV_EVENT_CLICKED, NULL);
lv_obj_add_event_cb(ui_cleanbutton, ui_event_cleanbutton, LV_EVENT_CLICKED, NULL);


}
