// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen9_screen_init(void)
{
    ui_Screen9 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen9, lv_color_hex(0x202429), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_minuteslabel = lv_label_create(ui_Screen9);
    lv_obj_set_width(ui_minuteslabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_minuteslabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_minuteslabel, -91);
    lv_obj_set_y(ui_minuteslabel, -158);
    lv_obj_set_align(ui_minuteslabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_minuteslabel, "Minutes");
    lv_obj_set_style_text_color(ui_minuteslabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_minuteslabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_minuteslabel, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_secondslabel = lv_label_create(ui_Screen9);
    lv_obj_set_width(ui_secondslabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_secondslabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_secondslabel, 89);
    lv_obj_set_y(ui_secondslabel, -158);
    lv_obj_set_align(ui_secondslabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_secondslabel, "Seconds");
    lv_obj_set_style_text_color(ui_secondslabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_secondslabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_secondslabel, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rollermin = lv_roller_create(ui_Screen9);
    lv_roller_set_options(ui_rollermin,
                          "0\n1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_rollermin, 132);
    lv_obj_set_height(ui_rollermin, 212);
    lv_obj_set_x(ui_rollermin, -92);
    lv_obj_set_y(ui_rollermin, -23);
    lv_obj_set_align(ui_rollermin, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_rollermin, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rollermin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rollermin, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_rollermin, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rollermin, lv_color_hex(0x202429), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rollermin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rollermin, lv_color_hex(0xE63029), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rollermin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_rollermin, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rollermin, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rollermin, &lv_font_montserrat_32, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rollermin, lv_color_hex(0xE63029), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rollermin, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_rollersec = lv_roller_create(ui_Screen9);
    lv_roller_set_options(ui_rollersec,
                          "10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_rollersec, 132);
    lv_obj_set_height(ui_rollersec, 208);
    lv_obj_set_x(ui_rollersec, 89);
    lv_obj_set_y(ui_rollersec, -21);
    lv_obj_set_align(ui_rollersec, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_rollersec, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rollersec, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rollersec, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_rollersec, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rollersec, lv_color_hex(0x202429), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rollersec, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rollersec, lv_color_hex(0xE63029), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rollersec, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_rollersec, lv_color_hex(0xE63029), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rollersec, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_setuptimebutton = lv_btn_create(ui_Screen9);
    lv_obj_set_width(ui_setuptimebutton, 354);
    lv_obj_set_height(ui_setuptimebutton, 132);
    lv_obj_set_x(ui_setuptimebutton, -8);
    lv_obj_set_y(ui_setuptimebutton, 159);
    lv_obj_set_align(ui_setuptimebutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_setuptimebutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_setuptimebutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_setuptimebutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_setuptimebutton, lv_color_hex(0x313841), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setuptimebutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_setuptimebutton, lv_color_hex(0xDF312A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_setuptimebutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_setuptimebutton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BACKTOSETUP3 = lv_label_create(ui_setuptimebutton);
    lv_obj_set_width(ui_BACKTOSETUP3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BACKTOSETUP3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BACKTOSETUP3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BACKTOSETUP3, "ENTER");
    lv_obj_set_style_text_font(ui_BACKTOSETUP3, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_setuptimebutton, ui_event_confirm_time, LV_EVENT_ALL, NULL);

}
